### PR TITLE
Fix issues in LG panel 

### PR DESCRIPTION
**Pull request by fyrplay**
Many OPO users were facing issues mentioned in 
this thread - https://forums.oneplus.net/threads/new-oneplus-one-with-lg-dci-display-major-issue.427499

This should fix it.

### CODE REVIEW

**Comment by maxwen** [comment]
"should" is no valid reason for a change. This needs to be tested and proved. And please use gerrit - we don't accept changes in pull requests.

**Comment by fyrplay** [comment]
it has been tested by me and other users with LG panel.

**Comment by maxwen** [comment]
With a clean omni build?

**Comment by fyrplay** [comment]
Yes.

**Comment by maxwen** [comment]
cool - thanks
still - we will handle this via gerrit
EDIT: https://gerrit.omnirom.org/#/c/17244/

**Comment by Entropy512** [comment]
Still needs to go through Gerrit.

**Comment by maxwen** [comment]
Is is https://gerrit.omnirom.org/#/c/17244/

**Pull request closed without merging**
